# Supervised learnings

# 🟥1.1 Derive an analytical solution to the regression problem. Use a vector form of the equation.

Аналитический метод — это способ решения задачи, при котором ответ находится по явной формуле за конечное число шагов (без итераций, без подбора параметров). Пример: корни квадратного уравнения по формуле 


Метод наименьших квадратов (МНК) — это критерий качества модели: выбираются такие коэффициенты, чтобы сумма квадратов ошибок была минимальной. МНК не является методом решения — это то, что мы хотим получить. Аналитическое решение МНК — это формула $\beta = (X^T X)^{-1} X^T y$

решить регрессионную задачу» означает «найти такие коэффициенты β, при которых ошибка минимальна». А ошибка — это функция потерь.

## Analytical solution to the linear regression problem

We have:
- $X$ — matrix of features (size $n \times m$)
- $y$ — vector of target values (size $n \times 1$)
- $\beta$ — vector of coefficients (size $m \times 1$)

The prediction is:
$$
\hat{y} = X\beta
$$

The loss function (sum of squared errors) is:
$$
L(\beta) = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 = (y - X\beta)^T (y - X\beta)
$$

### Step 1. Expand the loss function

$$
L(\beta) = (y^T - \beta^T X^T)(y - X\beta)
$$

$$
L(\beta) = y^T y - y^T X \beta - \beta^T X^T y + \beta^T X^T X \beta
$$

Note that $y^T X \beta$ is a scalar, so $y^T X \beta = (y^T X \beta)^T = \beta^T X^T y$. Therefore:

$$
L(\beta) = y^T y - 2\beta^T X^T y + \beta^T X^T X \beta
$$

### Step 2. Compute the gradient

The gradient of $L(\beta)$ with respect to $\beta$ is:

$$
\nabla L(\beta) = -2 X^T y + 2 X^T X \beta
$$

### Step 3. Set the gradient to zero (finding the minimum)

$$
-2 X^T y + 2 X^T X \beta = 0
$$

Divide by 2:

$$
- X^T y + X^T X \beta = 0
$$

$$
X^T X \beta = X^T y
$$

### Step 4. Solve for $\beta$

If $X^T X$ is invertible, multiply both sides by $(X^T X)^{-1}$:

$$
\boxed{\beta = (X^T X)^{-1} X^T y}
$$

This is the **analytical solution** (Ordinary Least Squares, OLS).

# 🟥1.2 What changes in the solution when L1 and L2 regularizations are added to the loss function.

**Problems without regularization:**
- If features are correlated, $X^T X$ can be non-invertible (no unique solution)
- Coefficients can become very large → overfitting
- The model is unstable (small changes in data cause large changes in predictions)

### 2. L2 Regularization (Ridge Regression)

**Adds a penalty on the sum of squared coefficients:**

$$
L_{\text{Ridge}}(\beta) = \underbrace{(y - X\beta)^T (y - X\beta)}_{\text{error}} + \lambda \underbrace{\sum_{j=1}^{m} \beta_j^2}_{\text{L2 penalty}}
$$

**What changes in the solution:**

The analytical solution becomes:

$$
\boxed{\beta = (X^T X + \lambda I)^{-1} X^T y}
$$

**Key properties of L2:**
- $X^T X + \lambda I$ is **always invertible** (even if $X^T X$ is singular)
- All coefficients are **reduced** (shrunk toward zero), but **none become exactly zero**
- Features with correlated effects get similar small weights
- $\lambda$ (lambda) is a hyperparameter that controls the strength of regularization

### 3. L1 Regularization (Lasso Regression)

**Adds a penalty on the sum of absolute coefficients:**

$$
L_{\text{Lasso}}(\beta) = \underbrace{(y - X\beta)^T (y - X\beta)}_{\text{error}} + \lambda \underbrace{\sum_{j=1}^{m} |\beta_j|}_{\text{L1 penalty}}
$$

**What changes in the solution:**

- **No closed-form analytical solution** (because $|\beta_j|$ is not differentiable at zero)
- The solution is found numerically (coordinate descent, gradient-based methods)
- Some coefficients become **exactly zero**

**Key properties of L1:**
- Performs **automatic feature selection** (zero coefficients = removed features)
- Produces sparse solutions (few non-zero coefficients)
- Useful when many features are irrelevant

# 🟥1.3 Explain why L1 regularization is often used to select features. Why are there many weights equal to 0 after the model is fit?

Отбор признаков (feature selection) — это процесс, при котором модель сама решает, какие входные данные важны, а какие нет.

L1 penalizes weights proportionally to their **absolute value** ($\lambda \sum |\beta_j|$).  
If a feature gives only a small benefit to the model, it's better to set its weight to **exactly zero** than to pay the penalty.

Geometric intuition

L1 constrains weights to a **diamond** (square rotated 45°). The diamond has **corners** on the axes. The optimal solution often lands at a corner → one weight becomes zero.

L2 constrains to a **circle**. A circle has **no corners**, so weights rarely become zero.

# 🟥1.4 Explain how you can use the same models (Linear regression, lasso, etc.) but make it possible to fit nonlinear dependencies.

нужно создать новые признаки, которые являются нелинейными функциями от исходных, а затем применить обычную линейную регрессию к этим новым признакам.

## How to fit nonlinear dependencies with linear models

### 1. The problem

Linear regression produces predictions of the form:

$$
\hat{y} = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \dots
$$

This is a straight line (2D), plane (3D), or hyperplane (higher dimensions).  
If the true relationship is curved (e.g., $y = x^2$), a linear model will fail.

### 2. The solution: create new features

Keep the model **linear in parameters**, but add columns to $X$ that are nonlinear functions of the original features.

**Example  $y = x^2$:**

Create the feature matrix:

$$
X = \begin{pmatrix} 1 & x & x^2 \end{pmatrix}
$$

The model becomes:

$$
\hat{y} = \beta_0 + \beta_1 x + \beta_2 x^2
$$

This is **polynomial regression**. The model is linear in $\beta$, so we solve it the same way (OLS, Ridge, Lasso).

### 3. Other examples of nonlinear features

| Original feature $x$ | New features | Can model |
| :--- | :--- | :--- |
| $x$ | $x, x^2, x^3$ | Polynomial relationships |
| $x$ | $\sin(x), \cos(x)$ | Periodic relationships |
| $x$ | $\log(x), \sqrt{x}, e^x$ | Logarithmic, power, exponential |
| $x_1, x_2$ | $x_1 \cdot x_2$ | Feature interactions |

# 🟧2. Introduction — make all the preprocessing staff from the previous lesson
# 🟧2.1 Import libraries.

In [140]:
import pandas as pd
from sklearn.model_selection import train_test_split
import re
from collections import Counter
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler, PolynomialFeatures

In [141]:
df = pd.read_json('data/train.json')
df

,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address,interest_level
4,1.0,1,8579a0b0d54db803821a35a4a615e97a,2016-06-16 05:55:27,Spacious 1 Bedroom 1 Bathroom in Williamsburg!...,145 Borinquen Place,"[Dining Room, Pre-War, Laundry in Building, Di...",40.7108,7170325,-73.9539,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/7170325_3bb5ac84...,2400,145 Borinquen Place,medium
6,1.0,2,b8e75fc949a6cd8225b455648a951712,2016-06-01 05:44:33,BRAND NEW GUT RENOVATED TRUE 2 BEDROOMFind you...,East 44th,"[Doorman, Elevator, Laundry in Building, Dishw...",40.7513,7092344,-73.9722,955db33477af4f40004820b4aed804a0,[https://photos.renthop.com/2/7092344_7663c19a...,3800,230 East 44th,low
9,1.0,2,cd759a988b8f23924b5a2058d5ab2b49,2016-06-14 15:19:59,**FLEX 2 BEDROOM WITH FULL PRESSURIZED WALL**L...,East 56th Street,"[Doorman, Elevator, Laundry in Building, Laund...",40.7575,7158677,-73.9625,c8b10a317b766204f08e613cef4ce7a0,[https://photos.renthop.com/2/7158677_c897a134...,3495,405 East 56th Street,medium
10,1.5,3,53a5b119ba8f7b61d4e010512e0dfc85,2016-06-24 07:54:24,A Brand New 3 Bedroom 1.5 bath ApartmentEnjoy ...,Metropolitan Avenue,[],40.7145,7211212,-73.9425,5ba989232d0489da1b5f2c45f6688adc,[https://photos.renthop.com/2/7211212_1ed4542e...,3000,792 Metropolitan Avenue,medium
15,1.0,0,bfb9405149bfff42a92980b594c28234,2016-06-28 03:50:23,Over-sized Studio w abundant closets. Availabl...,East 34th Street,"[Doorman, Elevator, Fitness Center, Laundry in...",40.7439,7225292,-73.9743,2c3b41f588fbb5234d8a1e885a436cfa,[https://photos.renthop.com/2/7225292_901f1984...,2795,340 East 34th Street,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124000,1.0,3,92bbbf38baadfde0576fc496bd41749c,2016-04-05 03:58:33,There is 700 square feet of recently renovated...,W 171 Street,"[Elevator, Dishwasher, Hardwood Floors]",40.8433,6824800,-73.9396,a61e21da3ba18c7a3d54cfdcc247e1f8,[https://photos.renthop.com/2/6824800_0682be16...,2800,620 W 171 Street,low
124002,1.0,2,5565db9b7cba3603834c4aa6f2950960,2016-04-02 02:25:31,"2 bedroom apartment with updated kitchen, rece...",Broadway,"[Common Outdoor Space, Cats Allowed, Dogs Allo...",40.8198,6813268,-73.9578,8f90e5e10e8a2d7cf997f016d89230eb,[https://photos.renthop.com/2/6813268_1e6fcc32...,2395,3333 Broadway,medium
124004,1.0,1,67997a128056ee1ed7d046bbb856e3c7,2016-04-26 05:42:03,No Brokers Fee * Never Lived 1 Bedroom 1 Bathr...,210 Brighton 15th St,"[Dining Room, Elevator, Pre-War, Laundry in Bu...",40.5765,6927093,-73.9554,a10db4590843d78c784171a107bdacb4,[https://photos.renthop.com/2/6927093_93a52104...,1850,210 Brighton 15th St,medium
124008,1.0,2,3c0574a740154806c18bdf1fddd3d966,2016-04-19 02:47:33,Wonderful Bright Chelsea 2 Bedroom apartment o...,West 21st Street,"[Pre-War, Laundry in Unit, Dishwasher, No Fee,...",40.7448,6892816,-74.0017,c3cd45f4381ac371507090e9ffabea80,[https://photos.renthop.com/2/6892816_1a8d087a...,4195,350 West 21st Street,medium
124009,1.0,3,d89f514c3ed0abaae52cba7017ac0701,2016-04-20 05:34:00,***PRIME MIDTOWN EAST OFF PARK AVE***TRUE 3 BE...,E 54th St,"[Dining Room, Elevator, Laundry in Building, D...",40.7594,6901023,-73.9712,e90f2ded843cdb2efd65ef47d9fc8029,[https://photos.renthop.com/2/6901023_02052d90...,4280,123 E 54th St,high

# 🟧2.2 Read Train and Test Parts.

In [142]:
X = df.drop(columns='price')
y = df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=21, test_size=0.2, shuffle=True)

# 🟨3 Intro data analysis part 2
# 🟨3.1 Let's generate additional features for better model quality. Consider a column called "Features". It consists of a list of highlights of the current flat.

# 🟨3.2 Remove unused symbols ([,], ', ", and space) from the column.

In [143]:
print(df['features'].dtype)
one_cell = df['features'].iloc[0]
print(type(one_cell))
print(one_cell[0])

object
<class 'list'>
Dining Room

In [144]:
def split_and_clean(item):
    if not isinstance(item, str):
        return []
    parts = re.split(r'[&/]+', item)
    cleaned_parts = []
    for part in parts:
        clean = re.sub(r'[^a-zA-Z0-9\-.,]', '', part).strip()
        if clean: 
            cleaned_parts.append(clean)
    return cleaned_parts

all_simple_features = []
for feature_list in df['features']:
    if isinstance(feature_list, list):
        for item in feature_list:
            all_simple_features.extend(split_and_clean(item))

# 🟨3.4 How many unique values does a result list contain?

In [145]:
unique_features_set = set(all_simple_features)

print(f"Всего уникальных значений: {len(unique_features_set)}")

with open('data/unique_features.txt', 'w', encoding='utf-8') as f:
    for feature in sorted(unique_features_set):
        f.write(feature + '\n')

Всего уникальных значений: 1627

# 🟨3.5 Let's get acquainted with the new library — Collections. With this package you could effectively get quantity statistics about your data.

# 🟨3.6 Count the most popular functions from our huge list and take the top 20 for this moment.

In [146]:
counter = Counter(all_simple_features)
top_20 = counter.most_common(20)

for feature, count in top_20:
    print(f"('{feature}', {count}),")

('Elevator', 25917),
('CatsAllowed', 23540),
('HardwoodFloors', 23527),
('DogsAllowed', 22035),
('Doorman', 20898),
('Dishwasher', 20428),
('NoFee', 18065),
('LaundryinBuilding', 16345),
('FitnessCenter', 13252),
('Pre-War', 9148),
('LaundryinUnit', 8738),
('RoofDeck', 6542),
('OutdoorSpace', 5268),
('DiningRoom', 5136),
('HighSpeedInternet', 4299),
('Balcony', 2992),
('SwimmingPool', 2730),
('LaundryInBuilding', 2593),
('NewConstruction', 2559),
('Terrace', 2283),

# 🟨3.7If everything is correct, you should get next values:  'Elevator', 'CatsAllowed', 'HardwoodFloors', 'DogsAllowed', 'Doorman', 'Dishwasher', 'NoFee', 'LaundryinBuilding', 'FitnessCenter', 'Pre-War', 'LaundryinUnit', 'RoofDeck', 'OutdoorSpace', 'DiningRoom', 'HighSpeedInternet', 'Balcony', 'SwimmingPool', 'LaundryInBuilding', 'NewConstruction', 'Terrace'.

# 🟨3.8 Now create 20 new features based on the top 20 values: 1 if the value is in the "Feature" column, otherwise 0.

In [147]:
top_20_names = [name for name, count in top_20]
df_model = pd.DataFrame()
df_model['bathrooms'] = df['bathrooms']
df_model['bedrooms'] = df['bedrooms']
for feature_name in top_20_names:
    df_model[f'has_{feature_name}'] = df['features'].apply(
        lambda lst: 1 if isinstance(lst, list) and any(
            feature_name in split_and_clean(item) for item in lst
        ) else 0
    )
df_model

,bathrooms,bedrooms,has_Elevator,has_CatsAllowed,has_HardwoodFloors,has_DogsAllowed,has_Doorman,has_Dishwasher,has_NoFee,has_LaundryinBuilding,...,has_LaundryinUnit,has_RoofDeck,has_OutdoorSpace,has_DiningRoom,has_HighSpeedInternet,has_Balcony,has_SwimmingPool,has_LaundryInBuilding,has_NewConstruction,has_Terrace
4,1.0,1,0,1,1,1,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0
6,1.0,2,1,0,1,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
9,1.0,2,1,0,1,0,1,1,0,1,...,1,0,0,0,0,0,0,0,0,0
10,1.5,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,1.0,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124000,1.0,3,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
124002,1.0,2,1,1,0,1,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0
124004,1.0,1,1,1,1,1,0,1,1,1,...,1,0,0,1,0,0,0,0,0,0
124008,1.0,2,0,0,0,0,0,1,1,0,...,1,0,1,0,0,0,0,0,0,0
124009,1.0,3,1,0,1,0,0,1,1,1,...,0,0,0,1,0,0,0,0,0,0

# 🟨3.9 Extend our feature set with 'bathrooms', 'bedrooms' and create a special variable feature_list with all feature names. Now we have 22 values. All models should be trained on these 22 features.

In [148]:
feature_list = ['bathrooms', 'bedrooms'] + top_20_names
feature_list

['bathrooms',
 'bedrooms',
 'Elevator',
 'CatsAllowed',
 'HardwoodFloors',
 'DogsAllowed',
 'Doorman',
 'Dishwasher',
 'NoFee',
 'LaundryinBuilding',
 'FitnessCenter',
 'Pre-War',
 'LaundryinUnit',
 'RoofDeck',
 'OutdoorSpace',
 'DiningRoom',
 'HighSpeedInternet',
 'Balcony',
 'SwimmingPool',
 'LaundryInBuilding',
 'NewConstruction',
 'Terrace']

In [149]:
X = df_model
y = df['price']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=21, test_size=0.2, shuffle=True)

# 🟩4. Models implementation — Linear regression

# 🟩4.1 Implement a Python class for a linear regression algorithm with two basic methods — fit and predict. Use stochastic gradient descent (SGD) to find optimal model weights. For better understanding, we recommend implementing separate versions of the algorithm with the analytical solution and non-stochastic gradient descent under the hood.

# 🟩4.2 What is determenistic model? Make SGD determenistic.

# 🟩4.3 Define the R squared (R2) coefficient and implement a function to calculate it.

In [150]:
class Linear:
    def __init__(self, learning_rate, n_epochs, random_state=21, penalty='none', 
                 alpha=1, l1_ratio=0.5, grad_clip=1.0):
        self.learning_rate = learning_rate
        self.n_epochs = n_epochs
        self.beta = None
        self.random_state = random_state
        self.penalty = penalty
        self.alpha = alpha
        self.l1_ratio = l1_ratio
        self.grad_clip = grad_clip

    def _regularization_gradient(self):
        grad_reg = np.zeros(len(self.beta))

        if self.penalty == 'Lasso':
            grad_reg[1:] = self.alpha * np.sign(self.beta[1:])
        elif self.penalty == 'Ridge':
            grad_reg[1:] = 2 * self.alpha * self.beta[1:]
        elif self.penalty == 'ElasticNet':
            grad_reg[1:] = (self.alpha * self.l1_ratio * np.sign(self.beta[1:]) + 
                           2 * self.alpha * (1 - self.l1_ratio) * self.beta[1:])
        return grad_reg
    
    def fit(self, X, y):
        if hasattr(X, 'values'):
            X = X.values
        if hasattr(y, 'values'):
            y = y.values

        if X is None or y is None:
            raise ValueError('X и y не могут быть None')
        if len(X) == 0:
            raise ValueError('Длина X не должна равняться 0')
        if len(X) != len(y):
            raise ValueError('Длины X и y не равны')
        
        ones = np.ones((X.shape[0], 1))
        X = np.hstack([ones, X])
        self.beta = np.zeros(X.shape[1])

        n = X.shape[0]
        np.random.seed(self.random_state) 
    
        for epoch in range(self.n_epochs):
            indexes = np.random.permutation(n)
            X = X[indexes]
            y = y[indexes]

            for i in range(n):
                X_batch = X[i:i+1]
                y_batch = y[i]

                y_pred = X_batch @ self.beta
                error = y_pred - y_batch

                grad_reg = self._regularization_gradient()
                gradient = 2 * X_batch.T @ error + grad_reg.flatten()
                
                # Клиппинг градиента (ограничиваем максимальное значение)
                grad_norm = np.linalg.norm(gradient)
                if grad_norm > self.grad_clip:
                    gradient = gradient * (self.grad_clip / grad_norm)
                
                self.beta = self.beta - self.learning_rate * gradient
                
                # Проверка на NaN/Inf
                if np.any(np.isnan(self.beta)) or np.any(np.isinf(self.beta)):
                    print(f"Warning: NaN/Inf at epoch {epoch}, iter {i}")
                    return self

        return self
    
    def predict(self, X):
        if hasattr(X, 'values'):
            X = X.values
        ones = np.ones((X.shape[0], 1))
        X = np.hstack([ones, X])
        return X @ self.beta

    def r2_score(self, y, y_pred):
        y_mean = np.mean(y)
        ss_res = np.sum((y - y_pred) ** 2)
        ss_tot = np.sum((y - y_mean) ** 2)
        if ss_tot == 0:
            return 1.0
        return 1 - (ss_res / ss_tot)

    def mae(self, y_true, y_pred):
        return np.mean(np.abs(y_true - y_pred))
    
    def rmse(self, y_true, y_pred):
        return np.sqrt(np.mean((y_true - y_pred) ** 2))

In [151]:
# Обучаем модель
model = Linear(learning_rate=0.01, n_epochs=100, random_state=21)
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

mae_train = model.mae(y_train, y_train_pred)
rmse_train = model.rmse(y_train, y_train_pred)
r2_train = model.r2_score(y_train, y_train_pred)

mae_test = model.mae(y_test, y_test_pred)
rmse_test = model.rmse(y_test, y_test_pred)
r2_test = model.r2_score(y_test, y_test_pred)


my_metrics = {
    'Train MAE':mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
}

In [152]:
sklearn_model = LinearRegression(fit_intercept=True)
sklearn_model.fit(X_train, y_train)

y_train_pred_sklearn = sklearn_model.predict(X_train)
y_test_pred_sklearn = sklearn_model.predict(X_test)

mae_train_sklearn =  mean_absolute_error(y_train, y_train_pred_sklearn)
rmse_train_sklearn = root_mean_squared_error(y_train, y_train_pred_sklearn)
r2_train_sklearn = r2_score(y_train, y_train_pred_sklearn)

mae_test_sklearn = mean_absolute_error(y_test, y_test_pred_sklearn)
rmse_test_sklearn = root_mean_squared_error(y_test, y_test_pred_sklearn)
r2_test_sklearn = r2_score(y_test, y_test_pred_sklearn)

sk_metrics = {
    'Train MAE':mae_train_sklearn,
    'Test MAE': mae_test_sklearn,
    'Train RMSE': rmse_train_sklearn,
    'Test RMSE': rmse_test_sklearn,
    'Train R2': r2_train_sklearn,
    'Test R2': r2_test_sklearn
}

In [153]:
metrics_table = []
metrics_table.append({
    'Model': 'My SGD',
    'Train MAE': my_metrics['Train MAE'],
    'Test MAE': my_metrics['Test MAE'],
    'Train RMSE': my_metrics['Train RMSE'],
    'Test RMSE': my_metrics['Test RMSE'],
    'Train R2': my_metrics['Train R2'],
    'Test R2': my_metrics['Test R2']
})

metrics_table.append({
    'Model': 'Sklearn LinearRegression',
    'Train MAE': sk_metrics['Train MAE'],
    'Test MAE': sk_metrics['Test MAE'],
    'Train RMSE': sk_metrics['Train RMSE'],
    'Test RMSE': sk_metrics['Test RMSE'],
    'Train R2': sk_metrics['Train R2'],
    'Test R2': sk_metrics['Test R2']
})

df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,0.003821,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856

# 🟦5.1 Regularized models implementation — Ridge, Lasso, ElasticNet

In [154]:
ridge_model = Linear(learning_rate=0.01, n_epochs=100, penalty = 'Ridge')
ridge_model.fit(X_train, y_train)
y_pred_ridge_train = ridge_model.predict(X_train)
y_pred_ridge_test = ridge_model.predict(X_test)

mae_train_ridge = ridge_model.mae(y_train, y_pred_ridge_train)
rmse_train_ridge =  ridge_model.rmse(y_train, y_pred_ridge_train)
r2_train_ridge = ridge_model.r2_score(y_train, y_pred_ridge_train)

mae_test_ridge = ridge_model.mae(y_test, y_pred_ridge_test)
rmse_test_ridge = ridge_model.rmse(y_test, y_pred_ridge_test)
r2_test_ridge = ridge_model.r2_score(y_test, y_pred_ridge_test)

metrics_table.append({
    'Model': 'Ridge (my)',
    'Train MAE': mae_train_ridge,
    'Test MAE': mae_test_ridge,
    'Train RMSE':rmse_train_ridge,
    'Test RMSE': rmse_test_ridge,
    'Train R2': r2_train_ridge,
    'Test R2': r2_test_ridge
})

In [155]:
lasso_model = Linear(learning_rate=0.01, n_epochs=100, penalty = 'Lasso')
lasso_model.fit(X_train, y_train)
y_pred_test_lasso = lasso_model.predict(X_test)
y_pred_train_lasso = lasso_model.predict(X_train)
y_pred_test_lasso = lasso_model.predict(X_test)


mae_train_lasso = lasso_model.mae(y_train, y_pred_train_lasso)
rmse_train_lasso = lasso_model.rmse(y_train, y_pred_train_lasso)
r2_train_lasso = lasso_model.r2_score(y_train, y_pred_train_lasso)

mae_test_lasso = lasso_model.mae(y_test, y_pred_test_lasso)
rmse_test_lasso = lasso_model.rmse(y_test, y_pred_test_lasso)
r2_test_lasso = lasso_model.r2_score(y_test, y_pred_test_lasso)

metrics_table.append({
    'Model': 'Lasso (my)',
    'Train MAE': mae_train_lasso,
    'Test MAE': mae_test_lasso,
    'Train RMSE':rmse_train_lasso,
    'Test RMSE': rmse_test_lasso,
    'Train R2': r2_train_lasso,
    'Test R2': r2_test_lasso
})

In [156]:
elastic_model = Linear(learning_rate=0.01, n_epochs=100, penalty = 'ElasticNet')
elastic_model.fit(X_train, y_train)
y_pred_train_elastic = elastic_model.predict(X_train)
y_pred_test_elastic = elastic_model.predict(X_test)


mae_train_elastic = elastic_model.mae(y_train, y_pred_train_elastic)
rmse_train_elastic = elastic_model.rmse(y_train, y_pred_train_elastic)
r2_train_elastic = elastic_model.r2_score(y_train, y_pred_train_elastic)

mae_test_elastic = elastic_model.mae(y_test, y_pred_test_elastic)
rmse_test_elastic = elastic_model.rmse(y_test, y_pred_test_elastic)
r2_test_elastic = elastic_model.r2_score(y_test, y_pred_test_elastic)

metrics_table.append({
    'Model': 'ElasticNet (my)',
    'Train MAE': mae_train_elastic,
    'Test MAE': mae_test_elastic,
    'Train RMSE':rmse_train_elastic,
    'Test RMSE': rmse_test_elastic,
    'Train R2': r2_train_elastic,
    'Test R2': r2_test_elastic
})

In [157]:
sk_ridge = Ridge()
sk_ridge.fit(X_train, y_train)
y_pred_train_sk_ridge = sk_ridge.predict(X_train)
y_pred_test_sk_ridge = sk_ridge.predict(X_test)

mae_train_sk_ridge = mean_absolute_error(y_train, y_pred_train_sk_ridge)
mae_test_sk_ridge = mean_absolute_error(y_test, y_pred_test_sk_ridge)
rmse_train_sk_ridge = root_mean_squared_error(y_train, y_pred_train_sk_ridge)
rmse_test_sk_ridge = root_mean_squared_error(y_test, y_pred_test_sk_ridge)
r2_train_sk_ridge = r2_score(y_train, y_pred_train_sk_ridge)
r2_test_sk_ridge = r2_score(y_test, y_pred_test_sk_ridge)

metrics_table.append({
    'Model': 'Ridge sklearn',
    'Train MAE': mae_train_sk_ridge,
    'Test MAE': mae_test_sk_ridge,
    'Train RMSE':rmse_train_sk_ridge,
    'Test RMSE': rmse_test_sk_ridge,
    'Train R2': r2_train_sk_ridge,
    'Test R2': r2_test_sk_ridge
})

In [158]:
sk_lasso = Lasso()
sk_lasso.fit(X_train, y_train)
y_pred_train_sk_lasso = sk_lasso.predict(X_train)
y_pred_test_sk_lasso = sk_lasso.predict(X_test)

mae_train_sk_lasso = mean_absolute_error(y_train, y_pred_train_sk_lasso)
mae_test_sk_lasso = mean_absolute_error(y_test, y_pred_test_sk_lasso)
rmse_train_sk_lasso = root_mean_squared_error(y_train, y_pred_train_sk_lasso)
rmse_test_sk_lasso = root_mean_squared_error(y_test, y_pred_test_sk_lasso)
r2_train_sk_lasso = r2_score(y_train, y_pred_train_sk_lasso)
r2_test_sk_lasso = r2_score(y_test, y_pred_test_sk_lasso)

metrics_table.append({
    'Model': 'Lasso sklearn',
    'Train MAE': mae_train_sk_lasso,
    'Test MAE': mae_test_sk_lasso,
    'Train RMSE':rmse_train_sk_lasso,
    'Test RMSE': rmse_test_sk_lasso,
    'Train R2': r2_train_sk_lasso,
    'Test R2': r2_test_sk_lasso
})

In [159]:
sk_elastic = ElasticNet()
sk_elastic.fit(X_train, y_train)
y_pred_train_sk_elastic = sk_elastic.predict(X_train)
y_pred_test_sk_elastic = sk_elastic.predict(X_test)

mae_train_sk_elastic = mean_absolute_error(y_train, y_pred_train_sk_elastic)
mae_test_sk_elastic = mean_absolute_error(y_test, y_pred_test_sk_elastic)
rmse_train_sk_elastic = root_mean_squared_error(y_train, y_pred_train_sk_elastic)
rmse_test_sk_elastic = root_mean_squared_error(y_test, y_pred_test_sk_elastic)
r2_train_sk_elastic = r2_score(y_train, y_pred_train_sk_elastic)
r2_test_sk_elastic = r2_score(y_test, y_pred_test_sk_elastic)

metrics_table.append({
    'Model': 'ElasticNet sklearn',
    'Train MAE': mae_train_sk_elastic,
    'Test MAE': mae_test_sk_elastic,
    'Train RMSE':rmse_train_sk_elastic,
    'Test RMSE': rmse_test_sk_elastic,
    'Train R2': r2_train_sk_elastic,
    'Test R2': r2_test_sk_elastic
})

In [160]:
df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,0.003821,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-0.000291,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,0.003740,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,0.000186,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,0.005495,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,0.005495,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,0.003883,0.280146

# 🟪6. Feature normalization

# 🟪6.1 First, write several examples of why and where feature normalization is mandatory and vice versa.

Нормализация необходима, если у нас много плюс минус одинаковых по важности числовых признаков, и чтобы модель показывала хорошие результаты нам надо привести это к одному формату. 
Например в диапозоне от 0 до 1. 
Если у нас есть кол-во комнат и цена за квадратный метр. Это два достаточно важных признака, без нормализации, вес будет распределяться неправильно. Модель будет считать, что цена важнее, так как числа больше. Это неправильно. 

Ее не следует использовать если данные представляют собой бинарную матрицу( как у нас), так как тогда значения могут принимать значения 0.5, -0.5 и параметр наличия лифта ( например)
становится неясным. 
Нормализация также не нужна в деревья и в ансамбле деверьев. Там другой способ построения моделей.

# 🟪6.2 Let's consider the first of the classical normalization methods — MinMaxScaler. Write a mathematical formula for this method.



$$
x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}
$$
​
 
​

In [161]:
class MinMax:
    def __init__(self):
        self.min_ = None
        self.max_ = None
        pass
    def fit(self, X):
        if hasattr(X, 'values'):
            X = X.values
        if len(X) == 0:
            raise ValueError("Пустой массив")

        self.min_ = np.min(X, axis=0)
        self.max_ = np.max(X, axis=0)
        return self
    def transform(self, X):
        if hasattr(X, 'values'):
            X = X.values
        if X is None:
            raise ValueError("Матрица X пустая")
        if len(X) == 0:
            raise ValueError("Кол-во строк 0")
        if self.min_ is None or self.max_ is None:
            raise ValueError("Сначала вызовите fit()")
        if X.shape[1] != len(self.min_) or X.shape[1] != len(self.max_):
            raise ValueError("оличество столбцов X не совпадает с количеством признаков в fit")
        numerator = X - self.min_
        denominator = self.max_ - self.min_
        denominator[denominator == 0] = 1
        zero_denom = denominator == 0
        if np.any(zero_denom):
            denominator[zero_denom] = 1
            numerator[:, zero_denom] = 0
        X_normalised = numerator/ denominator
        return X_normalised
    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

In [162]:
minmax_my = MinMax()
X_train_minmax_my = minmax_my.fit_transform(X_train)
X_test_minmax_my = minmax_my.transform(X_test)

minmax_sk = MinMaxScaler()
X_train_minmax_sk = minmax_sk.fit_transform(X_train)
X_test_minmax_sk = minmax_sk.transform(X_test)

$$
x_{std} = \frac{x - \mu}{\sigma}
$$

$$
\mu = \frac{1}{n} \sum_{i=1}^{n} x_i
$$

$$
\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (x_i - \mu)^2}
$$


x — исходное значение

μ (мю) — среднее арифметическое всех значений этого признака

σ (сигма) — стандартное отклонение всех значений этого признака

x std — стандартизированное значение

In [163]:
class StandardScalerMy:
    def __init__(self):
        self.mean_ = None
        self.std_ = None
    
    def fit(self, X):
        if hasattr(X, 'values'):
            X = X.values
        if len(X) == 0:
            raise ValueError("Пустой массив")
        
        self.mean_ = np.mean(X, axis=0)
        self.std_ = np.std(X, axis=0)
        return self
    
    def transform(self, X):
        if hasattr(X, 'values'):
            X = X.values
    
        if X is None:
            raise ValueError("Матрица X пустая")
        if len(X) == 0:
            raise ValueError("Кол-во строк 0")
        if self.mean_ is None or self.std_ is None:
            raise ValueError("Сначала вызовите fit()")
        if X.shape[1] != len(self.mean_):
            raise ValueError("Количество столбцов X не совпадает с количеством признаков в fit")
        
        numerator = X - self.mean_
        denominator = self.std_
        
        zero_std = denominator == 0
        if np.any(zero_std):
            denominator[zero_std] = 1
            numerator[:, zero_std] = 0
        X_standardised = numerator / denominator
        return X_standardised
    
    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

In [164]:
std_my = StandardScalerMy() 
X_train_my = std_my.fit_transform(X_train)
X_test_my = std_my.transform(X_test)

std_sk = StandardScaler()
X_train_sk = std_sk.fit_transform(X_train)
X_test_sk = std_sk.transform(X_test)

# ⬜️7. Fit custom and sklearn models with normalized data

## Linear (MinMax, my)

In [165]:
model = Linear(learning_rate=0.01, n_epochs=100, random_state=21)
model.fit(X_train_minmax_my, y_train)

y_pred_train = model.predict(X_train_minmax_my)
y_pred_test = model.predict(X_test_minmax_my)

mae_train = model.mae(y_train, y_pred_train)
rmse_train = model.rmse(y_train, y_pred_train)
r2_train = model.r2_score(y_train, y_pred_train)

mae_test = model.mae(y_test, y_pred_test)
rmse_test = model.rmse(y_test, y_pred_test)
r2_test = model.r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Linear (MinMax, my)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Linear (MinMax, sklearn)

In [166]:
model = LinearRegression()
model.fit(X_train_minmax_sk, y_train)

y_pred_train = model.predict(X_train_minmax_sk)
y_pred_test = model.predict(X_test_minmax_sk)

mae_train = mean_absolute_error(y_train, y_pred_train)
rmse_train = root_mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Linear (MinMax, sklearn)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Ridge (MinMax, my)

In [167]:
model = Linear(learning_rate=0.01, n_epochs=100, penalty='Ridge', alpha=1.0)
model.fit(X_train_minmax_my, y_train)

y_pred_train = model.predict(X_train_minmax_my)
y_pred_test = model.predict(X_test_minmax_my)

mae_train = model.mae(y_train, y_pred_train)
rmse_train = model.rmse(y_train, y_pred_train)
r2_train = model.r2_score(y_train, y_pred_train)

mae_test = model.mae(y_test, y_pred_test)
rmse_test = model.rmse(y_test, y_pred_test)
r2_test = model.r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Ridge (MinMax, my)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Ridge (MinMax, sklearn)

In [168]:
# Ridge с MinMax (sklearn)
model = Ridge(alpha=1.0)
model.fit(X_train_minmax_sk, y_train)

y_pred_train = model.predict(X_train_minmax_sk)
y_pred_test = model.predict(X_test_minmax_sk)

mae_train = mean_absolute_error(y_train, y_pred_train)
rmse_train = root_mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Ridge (MinMax, sklearn)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Lasso (MinMax, my)

In [169]:
model = Linear(learning_rate=0.01, n_epochs=100, penalty='Lasso', alpha=1.0)
model.fit(X_train_minmax_my, y_train)

y_pred_train = model.predict(X_train_minmax_my)
y_pred_test = model.predict(X_test_minmax_my)

mae_train = model.mae(y_train, y_pred_train)
rmse_train = model.rmse(y_train, y_pred_train)
r2_train = model.r2_score(y_train, y_pred_train)

mae_test = model.mae(y_test, y_pred_test)
rmse_test = model.rmse(y_test, y_pred_test)
r2_test = model.r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Lasso (MinMax, my)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Lasso (MinMax, sklearn)

In [170]:
model = Lasso(alpha=1.0, max_iter=10000)
model.fit(X_train_minmax_sk, y_train)

y_pred_train = model.predict(X_train_minmax_sk)
y_pred_test = model.predict(X_test_minmax_sk)

mae_train = mean_absolute_error(y_train, y_pred_train)
rmse_train = root_mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Lasso (MinMax, sklearn)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## ElasticNet (MinMax, my)

In [171]:
model = Linear(learning_rate=0.01, n_epochs=100, penalty='ElasticNet', alpha=1.0, l1_ratio=0.5)
model.fit(X_train_minmax_my, y_train)

y_pred_train = model.predict(X_train_minmax_my)
y_pred_test = model.predict(X_test_minmax_my)

mae_train = model.mae(y_train, y_pred_train)
rmse_train = model.rmse(y_train, y_pred_train)
r2_train = model.r2_score(y_train, y_pred_train)

mae_test = model.mae(y_test, y_pred_test)
rmse_test = model.rmse(y_test, y_pred_test)
r2_test = model.r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'ElasticNet (MinMax, my)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## ElasticNet (MinMax, sklearn)

In [172]:
model = ElasticNet(alpha=1.0, l1_ratio=0.5, max_iter=10000)
model.fit(X_train_minmax_sk, y_train)

y_pred_train = model.predict(X_train_minmax_sk)
y_pred_test = model.predict(X_test_minmax_sk)

mae_train = mean_absolute_error(y_train, y_pred_train)
rmse_train = root_mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'ElasticNet (MinMax, sklearn)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

In [173]:
df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,0.003821,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-0.000291,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,0.003740,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,0.000186,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,0.005495,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,0.005495,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,0.003883,0.280146
8,"Linear (MinMax, my)",1238.686682,1027.021494,24622.759240,2531.246918,0.001001,0.102628
9,"Linear (MinMax, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
10,"Ridge (MinMax, my)",1419.984929,1208.756867,24647.435255,2732.049909,-0.001002,-0.045396
11,"Ridge (MinMax, sklearn)",1247.519496,1049.259259,24567.316350,2194.405061,0.005495,0.325569
12,"Lasso (MinMax, my)",1245.221413,1032.997801,24623.938350,2540.703747,0.000905,0.095910
13,"Lasso (MinMax, sklearn)",1243.061515,1044.266393,24567.329587,2192.253178,0.005494,0.326891
14,"ElasticNet (MinMax, my)",1405.224468,1193.967918,24646.043253,2719.894676,-0.000889,-0.036115
15,"ElasticNet (MinMax, sklearn)",1508.694064,1286.219985,24620.553721,2576.776702,0.001180,0.070055

## Linear (Standard, my)

In [174]:
model = Linear(learning_rate=0.01, n_epochs=100, random_state=21)
model.fit(X_train_my, y_train)

y_pred_train = model.predict(X_train_my)
y_pred_test = model.predict(X_test_my)

mae_train = model.mae(y_train, y_pred_train)
rmse_train = model.rmse(y_train, y_pred_train)
r2_train = model.r2_score(y_train, y_pred_train)

mae_test = model.mae(y_test, y_pred_test)
rmse_test = model.rmse(y_test, y_pred_test)
r2_test = model.r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Linear (Standard, my)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Linear (Standard, sklearn)

In [175]:
model = LinearRegression()
model.fit(X_train_sk, y_train)

y_pred_train = model.predict(X_train_sk)
y_pred_test = model.predict(X_test_sk)

mae_train = mean_absolute_error(y_train, y_pred_train)
rmse_train = root_mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Linear (Standard, sklearn)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Ridge (Standard, my)

In [176]:
model = Linear(learning_rate=0.01, n_epochs=100, penalty='Ridge', alpha=1.0)
model.fit(X_train_my, y_train)

y_pred_train = model.predict(X_train_my)
y_pred_test = model.predict(X_test_my)

mae_train = model.mae(y_train, y_pred_train)
rmse_train = model.rmse(y_train, y_pred_train)
r2_train = model.r2_score(y_train, y_pred_train)

mae_test = model.mae(y_test, y_pred_test)
rmse_test = model.rmse(y_test, y_pred_test)
r2_test = model.r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Ridge (Standard, my)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Ridge (Standard, sklearn)

In [177]:
model = Ridge(alpha=1.0)
model.fit(X_train_sk, y_train)

y_pred_train = model.predict(X_train_sk)
y_pred_test = model.predict(X_test_sk)

mae_train = mean_absolute_error(y_train, y_pred_train)
rmse_train = root_mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Ridge (Standard, sklearn)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Lasso (Standard, my)

In [178]:
model = Linear(learning_rate=0.01, n_epochs=100, penalty='Lasso', alpha=1.0)
model.fit(X_train_my, y_train)

y_pred_train = model.predict(X_train_my)
y_pred_test = model.predict(X_test_my)

mae_train = model.mae(y_train, y_pred_train)
rmse_train = model.rmse(y_train, y_pred_train)
r2_train = model.r2_score(y_train, y_pred_train)

mae_test = model.mae(y_test, y_pred_test)
rmse_test = model.rmse(y_test, y_pred_test)
r2_test = model.r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Lasso (Standard, my)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## Lasso (Standard, sklearn)

In [179]:
model = Lasso(alpha=1.0, max_iter=10000)
model.fit(X_train_sk, y_train)

y_pred_train = model.predict(X_train_sk)
y_pred_test = model.predict(X_test_sk)

mae_train = mean_absolute_error(y_train, y_pred_train)
rmse_train = root_mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'Lasso (Standard, sklearn)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## ElasticNet (Standard, my)

In [180]:
model = Linear(learning_rate=0.01, n_epochs=100, penalty='ElasticNet', alpha=1.0, l1_ratio=0.5)
model.fit(X_train_my, y_train)

y_pred_train = model.predict(X_train_my)
y_pred_test = model.predict(X_test_my)

mae_train = model.mae(y_train, y_pred_train)
rmse_train = model.rmse(y_train, y_pred_train)
r2_train = model.r2_score(y_train, y_pred_train)

mae_test = model.mae(y_test, y_pred_test)
rmse_test = model.rmse(y_test, y_pred_test)
r2_test = model.r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'ElasticNet (Standard, my)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

## ElasticNet (Standard, sklearn)

In [181]:
model = ElasticNet(alpha=1.0, l1_ratio=0.5, max_iter=10000)
model.fit(X_train_sk, y_train)

y_pred_train = model.predict(X_train_sk)
y_pred_test = model.predict(X_test_sk)

mae_train = mean_absolute_error(y_train, y_pred_train)
rmse_train = root_mean_squared_error(y_train, y_pred_train)
r2_train = r2_score(y_train, y_pred_train)

mae_test = mean_absolute_error(y_test, y_pred_test)
rmse_test = root_mean_squared_error(y_test, y_pred_test)
r2_test = r2_score(y_test, y_pred_test)

metrics_table.append({
    'Model': 'ElasticNet (Standard, sklearn)',
    'Train MAE': mae_train,
    'Test MAE': mae_test,
    'Train RMSE': rmse_train,
    'Test RMSE': rmse_test,
    'Train R2': r2_train,
    'Test R2': r2_test
})

In [182]:
df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,0.003821,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-0.000291,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,0.003740,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,0.000186,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,0.005495,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,0.005495,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,0.003883,0.280146
8,"Linear (MinMax, my)",1238.686682,1027.021494,24622.759240,2531.246918,0.001001,0.102628
9,"Linear (MinMax, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
10,"Ridge (MinMax, my)",1419.984929,1208.756867,24647.435255,2732.049909,-0.001002,-0.045396
11,"Ridge (MinMax, sklearn)",1247.519496,1049.259259,24567.316350,2194.405061,0.005495,0.325569
12,"Lasso (MinMax, my)",1245.221413,1032.997801,24623.938350,2540.703747,0.000905,0.095910
13,"Lasso (MinMax, sklearn)",1243.061515,1044.266393,24567.329587,2192.253178,0.005494,0.326891
14,"ElasticNet (MinMax, my)",1405.224468,1193.967918,24646.043253,2719.894676,-0.000889,-0.036115
15,"ElasticNet (MinMax, sklearn)",1508.694064,1286.219985,24620.553721,2576.776702,0.001180,0.070055
16,"Linear (Standard, my)",1020.199609,814.426665,24586.978293,2206.687693,0.003902,0.317998
17,"Linear (Standard, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
18,"Ridge (Standard, my)",1297.667839,1086.299030,24633.199941,2606.041402,0.000154,0.048812
19,"Ridge (Standard, sklearn)",1247.436706,1049.490334,24567.313144,2193.929511,0.005495,0.325862
20,"Lasso (Standard, my)",1020.973155,814.667999,24587.408554,2210.063144,0.003868,0.315910
21,"Lasso (Standard, sklearn)",1245.724495,1047.602257,24567.314388,2192.954703,0.005495,0.326461
22,"ElasticNet (Standard, my)",1233.717847,1022.209662,24624.484808,2531.124773,0.000861,0.102714
23,"ElasticNet (Standard, sklearn)",1141.851741,933.765971,24573.512098,2169.335938,0.004993,0.340891

# 🟫8. Overfit models

In [183]:
poly = PolynomialFeatures(degree=10, include_bias=False)
X_base_train = X_train[['bathrooms', 'bedrooms']]
X_base_test = X_test[['bathrooms', 'bedrooms']]

X_train_poly = poly.fit_transform(X_base_train)
X_test_poly = poly.transform(X_base_test)

scaler = StandardScaler()
X_train_poly_scaled = scaler.fit_transform(X_train_poly)
X_test_poly_scaled = scaler.transform(X_test_poly)

binary_cols = [col for col in X_train.columns if col.startswith('has_')]

X_train_binary = X_train[binary_cols].values
X_test_binary = X_test[binary_cols].values

X_train_final = np.hstack([X_train_poly_scaled, X_train_binary])
X_test_final = np.hstack([X_test_poly_scaled, X_test_binary])

## LinearRegression(my, Polynomial)

In [184]:
model = Linear(learning_rate=0.000001, n_epochs=500, random_state=21, penalty='none')
model.fit(X_train_final, y_train)

y_pred_train = model.predict(X_train_final)
y_pred_test = model.predict(X_test_final)

metrics_table.append({
    'Model': 'Linear (Polynomial, degree=10, my)',
    'Train MAE': model.mae(y_train, y_pred_train),
    'Test MAE': model.mae(y_test, y_pred_test),
    'Train RMSE': model.rmse(y_train, y_pred_train),
    'Test RMSE': model.rmse(y_test, y_pred_test),
    'Train R2': model.r2_score(y_train, y_pred_train),
    'Test R2': model.r2_score(y_test, y_pred_test)
})

## Ridge ( my, Polynomial)

In [185]:
model = Linear(learning_rate=0.01, n_epochs=100, random_state=21, penalty='Ridge', alpha=1.0)
model.fit(X_train_final, y_train)

y_pred_train = model.predict(X_train_final)
y_pred_test = model.predict(X_test_final)

metrics_table.append({
    'Model': 'Ridge (Polynomial, degree=10, my)',
    'Train MAE': model.mae(y_train, y_pred_train),
    'Test MAE': model.mae(y_test, y_pred_test),
    'Train RMSE': model.rmse(y_train, y_pred_train),
    'Test RMSE': model.rmse(y_test, y_pred_test),
    'Train R2': model.r2_score(y_train, y_pred_train),
    'Test R2': model.r2_score(y_test, y_pred_test)
})

## Lasso ( my, Polynomial)

In [186]:
model = Linear(learning_rate=0.01, n_epochs=100, random_state=21, penalty='Lasso', alpha=1.0)
model.fit(X_train_final, y_train)

y_pred_train = model.predict(X_train_final)
y_pred_test = model.predict(X_test_final)

metrics_table.append({
    'Model': 'Lasso (Polynomial, degree=10, my)',
    'Train MAE': model.mae(y_train, y_pred_train),
    'Test MAE': model.mae(y_test, y_pred_test),
    'Train RMSE': model.rmse(y_train, y_pred_train),
    'Test RMSE': model.rmse(y_test, y_pred_test),
    'Train R2': model.r2_score(y_train, y_pred_train),
    'Test R2': model.r2_score(y_test, y_pred_test)
})

## ElasticNet ( my, Polynomial)

In [187]:
model = Linear(learning_rate=0.01, n_epochs=100, random_state=21, penalty='ElasticNet', alpha=1.0, l1_ratio=0.5)
model.fit(X_train_final, y_train)

y_pred_train = model.predict(X_train_final)
y_pred_test = model.predict(X_test_final)

metrics_table.append({
    'Model': 'ElasticNet (Polynomial, degree=10, my)',
    'Train MAE': model.mae(y_train, y_pred_train),
    'Test MAE': model.mae(y_test, y_pred_test),
    'Train RMSE': model.rmse(y_train, y_pred_train),
    'Test RMSE': model.rmse(y_test, y_pred_test),
    'Train R2': model.r2_score(y_train, y_pred_train),
    'Test R2': model.r2_score(y_test, y_pred_test)
})

## Linear (sklearn, Polinomial)

In [188]:
model = LinearRegression()
model.fit(X_train_final, y_train)

y_pred_train = model.predict(X_train_final)
y_pred_test = model.predict(X_test_final)

metrics_table.append({
    'Model': 'Linear (Polynomial, degree=10, sklearn)',
    'Train MAE': mean_absolute_error(y_train, y_pred_train),
    'Test MAE': mean_absolute_error(y_test, y_pred_test),
    'Train RMSE': root_mean_squared_error(y_train, y_pred_train),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test),
    'Train R2': r2_score(y_train, y_pred_train),
    'Test R2': r2_score(y_test, y_pred_test)
})

## Ridge (sklearn, Polinomial)

In [189]:
model = Ridge(alpha=1.0)
model.fit(X_train_final, y_train)

y_pred_train = model.predict(X_train_final)
y_pred_test = model.predict(X_test_final)

metrics_table.append({
    'Model': 'Ridge (Polynomial, degree=10, sklearn)',
    'Train MAE': mean_absolute_error(y_train, y_pred_train),
    'Test MAE': mean_absolute_error(y_test, y_pred_test),
    'Train RMSE': root_mean_squared_error(y_train, y_pred_train),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test),
    'Train R2': r2_score(y_train, y_pred_train),
    'Test R2': r2_score(y_test, y_pred_test)
})

## Lasso (sklearn, Polinomial)

In [190]:
model = Lasso(alpha=1.0, max_iter=10000)
model.fit(X_train_final, y_train)

y_pred_train = model.predict(X_train_final)
y_pred_test = model.predict(X_test_final)

metrics_table.append({
    'Model': 'Lasso (Polynomial, degree=10, sklearn)',
    'Train MAE': mean_absolute_error(y_train, y_pred_train),
    'Test MAE': mean_absolute_error(y_test, y_pred_test),
    'Train RMSE': root_mean_squared_error(y_train, y_pred_train),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test),
    'Train R2': r2_score(y_train, y_pred_train),
    'Test R2': r2_score(y_test, y_pred_test)
})

## ElasticNet (sklearn, Polinomial)

In [191]:
model = ElasticNet(alpha=1.0, l1_ratio=0.5, max_iter=10000)
model.fit(X_train_final, y_train)

y_pred_train = model.predict(X_train_final)
y_pred_test = model.predict(X_test_final)

metrics_table.append({
    'Model': 'ElasticNet (Polynomial, degree=10, sklearn)',
    'Train MAE': mean_absolute_error(y_train, y_pred_train),
    'Test MAE': mean_absolute_error(y_test, y_pred_test),
    'Train RMSE': root_mean_squared_error(y_train, y_pred_train),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test),
    'Train R2': r2_score(y_train, y_pred_train),
    'Test R2': r2_score(y_test, y_pred_test)
})

In [192]:
df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,0.003821,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-0.000291,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,0.003740,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,0.000186,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,0.005495,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,0.005495,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,0.003883,0.280146
8,"Linear (MinMax, my)",1238.686682,1027.021494,24622.759240,2531.246918,0.001001,0.102628
9,"Linear (MinMax, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
10,"Ridge (MinMax, my)",1419.984929,1208.756867,24647.435255,2732.049909,-0.001002,-0.045396
11,"Ridge (MinMax, sklearn)",1247.519496,1049.259259,24567.316350,2194.405061,0.005495,0.325569
12,"Lasso (MinMax, my)",1245.221413,1032.997801,24623.938350,2540.703747,0.000905,0.095910
13,"Lasso (MinMax, sklearn)",1243.061515,1044.266393,24567.329587,2192.253178,0.005494,0.326891
14,"ElasticNet (MinMax, my)",1405.224468,1193.967918,24646.043253,2719.894676,-0.000889,-0.036115
15,"ElasticNet (MinMax, sklearn)",1508.694064,1286.219985,24620.553721,2576.776702,0.001180,0.070055
16,"Linear (Standard, my)",1020.199609,814.426665,24586.978293,2206.687693,0.003902,0.317998
17,"Linear (Standard, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,0.005495,0.325856
18,"Ridge (Standard, my)",1297.667839,1086.299030,24633.199941,2606.041402,0.000154,0.048812
19,"Ridge (Standard, sklearn)",1247.436706,1049.490334,24567.313144,2193.929511,0.005495,0.325862
20,"Lasso (Standard, my)",1020.973155,814.667999,24587.408554,2210.063144,0.003868,0.315910
21,"Lasso (Standard, sklearn)",1245.724495,1047.602257,24567.314388,2192.954703,0.005495,0.326461
22,"ElasticNet (Standard, my)",1233.717847,1022.209662,24624.484808,2531.124773,0.000861,0.102714
23,"ElasticNet (Standard, sklearn)",1141.851741,933.765971,24573.512098,2169.335938,0.004993,0.340891
24,"Linear (Polynomial, degree=10, my)",3851.365543,3661.901637,24935.349300,4539.544017,-0.024525,-1.886212
25,"Ridge (Polynomial, degree=10, my)",1219.714792,1009.927767,24615.474417,2408.368412,0.001592,0.187638
26,"Lasso (Polynomial, degree=10, my)",1042.773064,830.040677,24596.768679,2339.823584,0.003109,0.233222
27,"ElasticNet (Polynomial, degree=10, my)",1151.548265,942.197074,24605.402265,2299.295376,0.002409,0.259554
28,"Linear (Polynomial, degree=10, sklearn)",1208.048000,16321.235427,24553.965817,961655.049046,0.006576,-129520.638150
29,"Ridge (Polynomial, degree=10, sklearn)",1208.234210,1001.534720,24555.673150,2136.042106,0.006437,0.360967
30,"Lasso (Polynomial, degree=10, sklearn)",1202.436440,996.056712,24556.084306,2104.681044,0.006404,0.379594
31,"ElasticNet (Polynomial, degree=10, sklearn)",1092.901763,877.931186,24568.488199,2011.942803,0.005400,0.433063

# ⬛️9. Native models

In [193]:
mean = y.mean()
median = y.median()
print(f'mean = {mean}')
print(f'median = {median}')

mean = 3830.174035500081
median = 3150.0

In [194]:
y_mean_train = np.mean(y_train)
y_median_train = np.median(y_train)

y_pred_train_mean = np.full_like(y_train, y_mean_train)
y_pred_test_mean = np.full_like(y_test, y_mean_train)

y_pred_train_median = np.full_like(y_train, y_median_train)
y_pred_test_median = np.full_like(y_test, y_median_train)

def add_model_metrics(model_name, y_pred_train, y_pred_test):
    metrics_table.append({
        'Model': model_name,
        'Train MAE': mean_absolute_error(y_train, y_pred_train),
        'Test MAE': mean_absolute_error(y_test, y_pred_test),
        'Train RMSE': root_mean_squared_error(y_train, y_pred_train),
        'Test RMSE': root_mean_squared_error(y_test, y_pred_test),
        'Train R2': r2_score(y_train, y_pred_train),
        'Test R2': r2_score(y_test, y_pred_test)
    })

add_model_metrics('Naive Mean', y_pred_train_mean, y_pred_test_mean)
add_model_metrics('Naive Median', y_pred_train_median, y_pred_test_median)

In [195]:
df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,3.821477e-03,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-2.909547e-04,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,3.739979e-03,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,1.857674e-04,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,5.495199e-03,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,5.494508e-03,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,3.883331e-03,0.280146
8,"Linear (MinMax, my)",1238.686682,1027.021494,24622.759240,2531.246918,1.001128e-03,0.102628
9,"Linear (MinMax, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
10,"Ridge (MinMax, my)",1419.984929,1208.756867,24647.435255,2732.049909,-1.002195e-03,-0.045396
11,"Ridge (MinMax, sklearn)",1247.519496,1049.259259,24567.316350,2194.405061,5.494940e-03,0.325569
12,"Lasso (MinMax, my)",1245.221413,1032.997801,24623.938350,2540.703747,9.054472e-04,0.095910
13,"Lasso (MinMax, sklearn)",1243.061515,1044.266393,24567.329587,2192.253178,5.493868e-03,0.326891
14,"ElasticNet (MinMax, my)",1405.224468,1193.967918,24646.043253,2719.894676,-8.891317e-04,-0.036115
15,"ElasticNet (MinMax, sklearn)",1508.694064,1286.219985,24620.553721,2576.776702,1.180085e-03,0.070055
16,"Linear (Standard, my)",1020.199609,814.426665,24586.978293,2206.687693,3.902440e-03,0.317998
17,"Linear (Standard, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
18,"Ridge (Standard, my)",1297.667839,1086.299030,24633.199941,2606.041402,1.537441e-04,0.048812
19,"Ridge (Standard, sklearn)",1247.436706,1049.490334,24567.313144,2193.929511,5.495199e-03,0.325862
20,"Lasso (Standard, my)",1020.973155,814.667999,24587.408554,2210.063144,3.867577e-03,0.315910
21,"Lasso (Standard, sklearn)",1245.724495,1047.602257,24567.314388,2192.954703,5.495099e-03,0.326461
22,"ElasticNet (Standard, my)",1233.717847,1022.209662,24624.484808,2531.124773,8.611026e-04,0.102714
23,"ElasticNet (Standard, sklearn)",1141.851741,933.765971,24573.512098,2169.335938,4.993259e-03,0.340891
24,"Linear (Polynomial, degree=10, my)",3851.365543,3661.901637,24935.349300,4539.544017,-2.452479e-02,-1.886212
25,"Ridge (Polynomial, degree=10, my)",1219.714792,1009.927767,24615.474417,2408.368412,1.592162e-03,0.187638
26,"Lasso (Polynomial, degree=10, my)",1042.773064,830.040677,24596.768679,2339.823584,3.109002e-03,0.233222
27,"ElasticNet (Polynomial, degree=10, my)",1151.548265,942.197074,24605.402265,2299.295376,2.409052e-03,0.259554
28,"Linear (Polynomial, degree=10, sklearn)",1208.048000,16321.235427,24553.965817,961655.049046,6.575527e-03,-129520.638150
29,"Ridge (Polynomial, degree=10, sklearn)",1208.234210,1001.534720,24555.673150,2136.042106,6.437369e-03,0.360967
30,"Lasso (Polynomial, degree=10, sklearn)",1202.436440,996.056712,24556.084306,2104.681044,6.404097e-03,0.379594
31,"ElasticNet (Polynomial, degree=10, sklearn)",1092.901763,877.931186,24568.488199,2011.942803,5.400063e-03,0.433063
32,Naive Mean,1609.879132,1385.803971,24635.093764,2678.758284,-9.658940e-14,-0.005011
33,Naive Median,1442.898154,1230.142336,24645.554970,2723.903833,-8.494732e-04,-0.039172

# 🔳10. Compare results

1.Print your final tables

2.What is the best model?

3.Which is the most stable model?

In [196]:
best_r2 = df_metrics_table.loc[df_metrics_table['Test R2'].idxmax()]
print("Лучшая модель по R²:")
print(best_r2[['Model', 'Test R2', 'Test MAE', 'Test RMSE']])

best_mae = df_metrics_table.loc[df_metrics_table['Test MAE'].idxmin()]
print("\nЛучшая модель по MAE:")
print(best_mae[['Model', 'Test R2', 'Test MAE', 'Test RMSE']])

best_rmse = df_metrics_table.loc[df_metrics_table['Test RMSE'].idxmin()]
print("\nЛучшая модель по RMSE:")
print(best_rmse[['Model', 'Test R2', 'Test MAE', 'Test RMSE']])

Лучшая модель по R²:
Model        ElasticNet (Polynomial, degree=10, sklearn)
Test R2                                         0.433063
Test MAE                                      877.931186
Test RMSE                                    2011.942803
Name: 31, dtype: object

Лучшая модель по MAE:
Model        Linear (Standard, my)
Test R2                   0.317998
Test MAE                814.426665
Test RMSE              2206.687693
Name: 16, dtype: object

Лучшая модель по RMSE:
Model        ElasticNet (Polynomial, degree=10, sklearn)
Test R2                                         0.433063
Test MAE                                      877.931186
Test RMSE                                    2011.942803
Name: 31, dtype: object

The best model is ElasticNet ( Polinomial, degree=10, sklearn)

In [197]:
temp_df = df_metrics_table.copy()
temp_df['R2_gap'] = abs(temp_df['Train R2'] - temp_df['Test R2'])
temp_df = temp_df[~temp_df['Model'].str.contains('Naive')]
stable_models = temp_df.sort_values('R2_gap')

print("Самые стабильные модели:")
print(stable_models[['Model', 'Train R2', 'Test R2', 'R2_gap']].head(10))

Самые стабильные модели:
                                Model  Train R2   Test R2    R2_gap
2                          Ridge (my) -0.000291  0.010028  0.010319
14            ElasticNet (MinMax, my) -0.000889 -0.036115  0.035226
10                 Ridge (MinMax, my) -0.001002 -0.045396  0.044394
4                     ElasticNet (my)  0.000186  0.047151  0.046965
18               Ridge (Standard, my)  0.000154  0.048812  0.048658
15       ElasticNet (MinMax, sklearn)  0.001180  0.070055  0.068875
12                 Lasso (MinMax, my)  0.000905  0.095910  0.095004
8                 Linear (MinMax, my)  0.001001  0.102628  0.101626
22          ElasticNet (Standard, my)  0.000861  0.102714  0.101853
25  Ridge (Polynomial, degree=10, my)  0.001592  0.187638  0.186046

# ⭐️11. Addition task

# ⭐️11.1. There are some tricks with the target variable for better model quality. If we have a distribution with a heavy tail, you can use a monotone function to "improve" the distribution. In practice, you can use logarithmic functions. We recommend that you do this exercise and compare the results. But don't forget to do the inverse transformation if you want to compare metrics.

In [ ]:
model = ElasticNet(alpha=1.0, l1_ratio=0.5, max_iter=10000)
y_train_log = np.log1p(y_train)
y_test_log = np.log1p(y_test)

model.fit(X_train, y_train_log)
y_pred_train_log = model.predict(X_train)
y_pred_test_log = model.predict(X_test)

y_pred_train = np.expm1(y_pred_train_log)
y_pred_test = np.expm1(y_pred_test_log) 

metrics_table.append({
    'Model': 'Log func',
    'Train MAE': mean_absolute_error(y_train, y_pred_train),
    'Test MAE': mean_absolute_error(y_test, y_pred_test),
    'Train RMSE': root_mean_squared_error(y_train, y_pred_train),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test),
    'Train R2': r2_score(y_train, y_pred_train),
    'Test R2': r2_score(y_test, y_pred_test)
})

In [199]:
df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,3.821477e-03,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-2.909547e-04,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,3.739979e-03,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,1.857674e-04,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,5.495199e-03,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,5.494508e-03,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,3.883331e-03,0.280146
8,"Linear (MinMax, my)",1238.686682,1027.021494,24622.759240,2531.246918,1.001128e-03,0.102628
9,"Linear (MinMax, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
10,"Ridge (MinMax, my)",1419.984929,1208.756867,24647.435255,2732.049909,-1.002195e-03,-0.045396
11,"Ridge (MinMax, sklearn)",1247.519496,1049.259259,24567.316350,2194.405061,5.494940e-03,0.325569
12,"Lasso (MinMax, my)",1245.221413,1032.997801,24623.938350,2540.703747,9.054472e-04,0.095910
13,"Lasso (MinMax, sklearn)",1243.061515,1044.266393,24567.329587,2192.253178,5.493868e-03,0.326891
14,"ElasticNet (MinMax, my)",1405.224468,1193.967918,24646.043253,2719.894676,-8.891317e-04,-0.036115
15,"ElasticNet (MinMax, sklearn)",1508.694064,1286.219985,24620.553721,2576.776702,1.180085e-03,0.070055
16,"Linear (Standard, my)",1020.199609,814.426665,24586.978293,2206.687693,3.902440e-03,0.317998
17,"Linear (Standard, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
18,"Ridge (Standard, my)",1297.667839,1086.299030,24633.199941,2606.041402,1.537441e-04,0.048812
19,"Ridge (Standard, sklearn)",1247.436706,1049.490334,24567.313144,2193.929511,5.495199e-03,0.325862
20,"Lasso (Standard, my)",1020.973155,814.667999,24587.408554,2210.063144,3.867577e-03,0.315910
21,"Lasso (Standard, sklearn)",1245.724495,1047.602257,24567.314388,2192.954703,5.495099e-03,0.326461
22,"ElasticNet (Standard, my)",1233.717847,1022.209662,24624.484808,2531.124773,8.611026e-04,0.102714
23,"ElasticNet (Standard, sklearn)",1141.851741,933.765971,24573.512098,2169.335938,4.993259e-03,0.340891
24,"Linear (Polynomial, degree=10, my)",3851.365543,3661.901637,24935.349300,4539.544017,-2.452479e-02,-1.886212
25,"Ridge (Polynomial, degree=10, my)",1219.714792,1009.927767,24615.474417,2408.368412,1.592162e-03,0.187638
26,"Lasso (Polynomial, degree=10, my)",1042.773064,830.040677,24596.768679,2339.823584,3.109002e-03,0.233222
27,"ElasticNet (Polynomial, degree=10, my)",1151.548265,942.197074,24605.402265,2299.295376,2.409052e-03,0.259554
28,"Linear (Polynomial, degree=10, sklearn)",1208.048000,16321.235427,24553.965817,961655.049046,6.575527e-03,-129520.638150
29,"Ridge (Polynomial, degree=10, sklearn)",1208.234210,1001.534720,24555.673150,2136.042106,6.437369e-03,0.360967
30,"Lasso (Polynomial, degree=10, sklearn)",1202.436440,996.056712,24556.084306,2104.681044,6.404097e-03,0.379594
31,"ElasticNet (Polynomial, degree=10, sklearn)",1092.901763,877.931186,24568.488199,2011.942803,5.400063e-03,0.433063
32,Naive Mean,1609.879132,1385.803971,24635.093764,2678.758284,-9.658940e-14,-0.005011
33,Naive Median,1442.898154,1230.142336,24645.554970,2723.903833,-8.494732e-04,-0.039172
34,Log func,1450.187821,1235.635929,24641.926891,2700.544437,-5.548243e-04,-0.021425

# ⭐️11.2 The next trick is outliers. The angle of the linear regression line depends strongly on outliers. And often you should remove these points from !allert! only training data. You should explain why they were removed from the training sample only.  We recommend that you do this exercise and compare the results.

Выбросы удаляются только из обучающей выборки, потому что они могут исказить веса модели (особенно в линейной регрессии). Однако тестовая выборка должна оставаться нетронутой, чтобы отражать реальные условия — в том числе возможные экстремальные значения. Удаление выбросов из теста привело бы к оптимистичной и нечестной оценке качества модели

In [200]:
lower = y_train.quantile(0.01)
upper = y_train.quantile(0.99)

mask = (y_train >= lower) & (y_train <= upper)
X_train_clean = X_train[mask]
y_train_clean = y_train[mask]

model = ElasticNet(alpha=1.0, l1_ratio=0.5, max_iter=10000)
model.fit(X_train_clean, y_train_clean)
y_pred_train_clean = model.predict(X_train_clean)
y_pred_test_clean = model.predict(X_test)

metrics_table.append({
    'Model': ' ElasticNet (outliers removed)',
    'Train MAE': mean_absolute_error(y_train_clean, y_pred_train_clean),
    'Test MAE': mean_absolute_error(y_test, y_pred_test),
    'Train RMSE': root_mean_squared_error(y_train_clean, y_pred_train_clean),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test),
    'Train R2': r2_score(y_train_clean, y_pred_train_clean),
    'Test R2': r2_score(y_test, y_pred_test)
})

df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,3.821477e-03,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-2.909547e-04,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,3.739979e-03,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,1.857674e-04,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,5.495199e-03,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,5.494508e-03,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,3.883331e-03,0.280146
8,"Linear (MinMax, my)",1238.686682,1027.021494,24622.759240,2531.246918,1.001128e-03,0.102628
9,"Linear (MinMax, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
10,"Ridge (MinMax, my)",1419.984929,1208.756867,24647.435255,2732.049909,-1.002195e-03,-0.045396
11,"Ridge (MinMax, sklearn)",1247.519496,1049.259259,24567.316350,2194.405061,5.494940e-03,0.325569
12,"Lasso (MinMax, my)",1245.221413,1032.997801,24623.938350,2540.703747,9.054472e-04,0.095910
13,"Lasso (MinMax, sklearn)",1243.061515,1044.266393,24567.329587,2192.253178,5.493868e-03,0.326891
14,"ElasticNet (MinMax, my)",1405.224468,1193.967918,24646.043253,2719.894676,-8.891317e-04,-0.036115
15,"ElasticNet (MinMax, sklearn)",1508.694064,1286.219985,24620.553721,2576.776702,1.180085e-03,0.070055
16,"Linear (Standard, my)",1020.199609,814.426665,24586.978293,2206.687693,3.902440e-03,0.317998
17,"Linear (Standard, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
18,"Ridge (Standard, my)",1297.667839,1086.299030,24633.199941,2606.041402,1.537441e-04,0.048812
19,"Ridge (Standard, sklearn)",1247.436706,1049.490334,24567.313144,2193.929511,5.495199e-03,0.325862
20,"Lasso (Standard, my)",1020.973155,814.667999,24587.408554,2210.063144,3.867577e-03,0.315910
21,"Lasso (Standard, sklearn)",1245.724495,1047.602257,24567.314388,2192.954703,5.495099e-03,0.326461
22,"ElasticNet (Standard, my)",1233.717847,1022.209662,24624.484808,2531.124773,8.611026e-04,0.102714
23,"ElasticNet (Standard, sklearn)",1141.851741,933.765971,24573.512098,2169.335938,4.993259e-03,0.340891
24,"Linear (Polynomial, degree=10, my)",3851.365543,3661.901637,24935.349300,4539.544017,-2.452479e-02,-1.886212
25,"Ridge (Polynomial, degree=10, my)",1219.714792,1009.927767,24615.474417,2408.368412,1.592162e-03,0.187638
26,"Lasso (Polynomial, degree=10, my)",1042.773064,830.040677,24596.768679,2339.823584,3.109002e-03,0.233222
27,"ElasticNet (Polynomial, degree=10, my)",1151.548265,942.197074,24605.402265,2299.295376,2.409052e-03,0.259554
28,"Linear (Polynomial, degree=10, sklearn)",1208.048000,16321.235427,24553.965817,961655.049046,6.575527e-03,-129520.638150
29,"Ridge (Polynomial, degree=10, sklearn)",1208.234210,1001.534720,24555.673150,2136.042106,6.437369e-03,0.360967
30,"Lasso (Polynomial, degree=10, sklearn)",1202.436440,996.056712,24556.084306,2104.681044,6.404097e-03,0.379594
31,"ElasticNet (Polynomial, degree=10, sklearn)",1092.901763,877.931186,24568.488199,2011.942803,5.400063e-03,0.433063
32,Naive Mean,1609.879132,1385.803971,24635.093764,2678.758284,-9.658940e-14,-0.005011
33,Naive Median,1442.898154,1230.142336,24645.554970,2723.903833,-8.494732e-04,-0.039172
34,Log func,1450.187821,1235.635929,24641.926891,2700.544437,-5.548243e-04,-0.021425
35,ElasticNet (outliers removed),806.924444,1235.635929,1190.192610,2700.544437,4.461407e-01,-0.021425

In [201]:
naive_mean = y_train_clean.mean()
y_pred_naive_test = np.full_like(y_test, naive_mean)
y_pred_naive_train = np.full_like(y_train_clean, naive_mean)

metrics_table.append({
    'Model': 'Naive Mean (outliers removed)',
    'Train MAE': mean_absolute_error(y_train_clean, y_pred_naive_train),
    'Test MAE': mean_absolute_error(y_test, y_pred_naive_test),
    'Train RMSE': root_mean_squared_error(y_train_clean, y_pred_naive_train),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_naive_test),
    'Train R2': r2_score(y_train_clean, y_pred_naive_train),
    'Test R2': r2_score(y_test, y_pred_naive_test)
})

df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,3.821477e-03,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-2.909547e-04,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,3.739979e-03,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,1.857674e-04,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,5.495199e-03,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,5.494508e-03,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,3.883331e-03,0.280146
8,"Linear (MinMax, my)",1238.686682,1027.021494,24622.759240,2531.246918,1.001128e-03,0.102628
9,"Linear (MinMax, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
10,"Ridge (MinMax, my)",1419.984929,1208.756867,24647.435255,2732.049909,-1.002195e-03,-0.045396
11,"Ridge (MinMax, sklearn)",1247.519496,1049.259259,24567.316350,2194.405061,5.494940e-03,0.325569
12,"Lasso (MinMax, my)",1245.221413,1032.997801,24623.938350,2540.703747,9.054472e-04,0.095910
13,"Lasso (MinMax, sklearn)",1243.061515,1044.266393,24567.329587,2192.253178,5.493868e-03,0.326891
14,"ElasticNet (MinMax, my)",1405.224468,1193.967918,24646.043253,2719.894676,-8.891317e-04,-0.036115
15,"ElasticNet (MinMax, sklearn)",1508.694064,1286.219985,24620.553721,2576.776702,1.180085e-03,0.070055
16,"Linear (Standard, my)",1020.199609,814.426665,24586.978293,2206.687693,3.902440e-03,0.317998
17,"Linear (Standard, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
18,"Ridge (Standard, my)",1297.667839,1086.299030,24633.199941,2606.041402,1.537441e-04,0.048812
19,"Ridge (Standard, sklearn)",1247.436706,1049.490334,24567.313144,2193.929511,5.495199e-03,0.325862
20,"Lasso (Standard, my)",1020.973155,814.667999,24587.408554,2210.063144,3.867577e-03,0.315910
21,"Lasso (Standard, sklearn)",1245.724495,1047.602257,24567.314388,2192.954703,5.495099e-03,0.326461
22,"ElasticNet (Standard, my)",1233.717847,1022.209662,24624.484808,2531.124773,8.611026e-04,0.102714
23,"ElasticNet (Standard, sklearn)",1141.851741,933.765971,24573.512098,2169.335938,4.993259e-03,0.340891
24,"Linear (Polynomial, degree=10, my)",3851.365543,3661.901637,24935.349300,4539.544017,-2.452479e-02,-1.886212
25,"Ridge (Polynomial, degree=10, my)",1219.714792,1009.927767,24615.474417,2408.368412,1.592162e-03,0.187638
26,"Lasso (Polynomial, degree=10, my)",1042.773064,830.040677,24596.768679,2339.823584,3.109002e-03,0.233222
27,"ElasticNet (Polynomial, degree=10, my)",1151.548265,942.197074,24605.402265,2299.295376,2.409052e-03,0.259554
28,"Linear (Polynomial, degree=10, sklearn)",1208.048000,16321.235427,24553.965817,961655.049046,6.575527e-03,-129520.638150
29,"Ridge (Polynomial, degree=10, sklearn)",1208.234210,1001.534720,24555.673150,2136.042106,6.437369e-03,0.360967
30,"Lasso (Polynomial, degree=10, sklearn)",1202.436440,996.056712,24556.084306,2104.681044,6.404097e-03,0.379594
31,"ElasticNet (Polynomial, degree=10, sklearn)",1092.901763,877.931186,24568.488199,2011.942803,5.400063e-03,0.433063
32,Naive Mean,1609.879132,1385.803971,24635.093764,2678.758284,-9.658940e-14,-0.005011
33,Naive Median,1442.898154,1230.142336,24645.554970,2723.903833,-8.494732e-04,-0.039172
34,Log func,1450.187821,1235.635929,24641.926891,2700.544437,-5.548243e-04,-0.021425
35,ElasticNet (outliers removed),806.924444,1235.635929,1190.192610,2700.544437,4.461407e-01,-0.021425
36,Naive Mean (outliers removed),1138.999587,1276.052477,1599.254339,2676.049545,-9.495353e-08,-0.002979

In [202]:
outliers_train = (y_train > 10000).sum()
print("Выбросов в трейне (price > 10k):", outliers_train)

Выбросов в трейне (price > 10k): 714

# ⭐️11.3 It will also be a useful exercise to implement a linear regression algorithm with batch and mini-batch training or analytical solution (as mentioned in 4.1).

In [203]:
class MyLinearRegression():
    def __init__(self, method='analytical', learning_rate=0.01, n_epochs=1000, batch_size=None, random_state=21):
        self.method = method
        self.learning_rate = learning_rate
        self.n_epochs = n_epochs
        self.batch_size = batch_size
        self.random_state = random_state
        self.weights_ = None
        self.bias_ = None
        
    def _add_bias(self, X):
        return np.c_[np.ones(X.shape[0]), X]
    
    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)
        
        if self.method == 'analytical':
            self._fit_analytical(X, y)
        elif self.method in ['batch', 'mini-batch']:
            self._fit_gradient_descent(X, y)
        else:
            raise ValueError("Method must be 'analytical', 'batch', or 'mini-batch'")
            
        return self
    
    def _fit_analytical(self, X, y):
        X_b = self._add_bias(X)
        self.weights_ = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y
        self.bias_ = self.weights_[0]
        self.weights_ = self.weights_[1:]
        
    def _fit_gradient_descent(self, X, y):
        np.random.seed(self.random_state)
        n_samples, n_features = X.shape
        
        self.weights_ = np.random.normal(0, 0.01, n_features)
        self.bias_ = 0
        
        if self.method == 'batch' or self.batch_size is None:
            batch_size = n_samples
        else:  
            batch_size = min(self.batch_size, n_samples)
            
        for epoch in range(self.n_epochs):
            if self.method == 'mini-batch':
                indices = np.random.permutation(n_samples)
                X_shuffled = X[indices]
                y_shuffled = y[indices]
            else:
                X_shuffled = X
                y_shuffled = y
                
            for i in range(0, n_samples, batch_size):
                X_batch = X_shuffled[i:i+batch_size]
                y_batch = y_shuffled[i:i+batch_size]
                
                y_pred = X_batch @ self.weights_ + self.bias_
                
                dw = (2 / len(X_batch)) * X_batch.T @ (y_pred - y_batch)
                db = (2 / len(X_batch)) * np.sum(y_pred - y_batch)
                
                self.weights_ -= self.learning_rate * dw
                self.bias_ -= self.learning_rate * db
                
    def predict(self, X):
        X = np.array(X)
        return X @ self.weights_ + self.bias_

In [204]:
model_analytical = MyLinearRegression(method='analytical')
model_analytical.fit(X_train, y_train)
y_pred_train_analytical = model_analytical.predict(X_train)
y_pred_test_analytical = model_analytical.predict(X_test)

metrics_table.append({
    'Model': 'Linear (Analytical)',
    'Train MAE': mean_absolute_error(y_train, y_pred_train_analytical),
    'Test MAE': mean_absolute_error(y_test, y_pred_test_analytical),
    'Train RMSE': root_mean_squared_error(y_train, y_pred_train_analytical),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test_analytical),
    'Train R2': r2_score(y_train, y_pred_train_analytical),
    'Test R2': r2_score(y_test, y_pred_test_analytical)
})

model_batch = MyLinearRegression(
    method='batch', 
    learning_rate=0.01, 
    n_epochs=1000,
    random_state=21
)
model_batch.fit(X_train, y_train)
y_pred_train_batch = model_batch.predict(X_train)
y_pred_test_batch = model_batch.predict(X_test)

metrics_table.append({
    'Model': 'Linear (Batch GD)',
    'Train MAE': mean_absolute_error(y_train, y_pred_train_batch),
    'Test MAE': mean_absolute_error(y_test, y_pred_test_batch),
    'Train RMSE': root_mean_squared_error(y_train, y_pred_train_batch),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test_batch),
    'Train R2': r2_score(y_train, y_pred_train_batch),
    'Test R2': r2_score(y_test, y_pred_test_batch)
})

model_mini = MyLinearRegression(
    method='mini-batch', 
    learning_rate=0.01, 
    n_epochs=1000,
    batch_size=32,
    random_state=21
)
model_mini.fit(X_train, y_train)
y_pred_train_mini = model_mini.predict(X_train)
y_pred_test_mini = model_mini.predict(X_test)

metrics_table.append({
    'Model': 'Linear (Mini-batch GD)',
    'Train MAE': mean_absolute_error(y_train, y_pred_train_mini),
    'Test MAE': mean_absolute_error(y_test, y_pred_test_mini),
    'Train RMSE': root_mean_squared_error(y_train, y_pred_train_mini),
    'Test RMSE': root_mean_squared_error(y_test, y_pred_test_mini),
    'Train R2': r2_score(y_train, y_pred_train_mini),
    'Test R2': r2_score(y_test, y_pred_test_mini)
})

In [205]:
df_metrics_table = pd.DataFrame(metrics_table)
df_metrics_table

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,Train R2,Test R2
0,My SGD,1023.422554,815.519539,24587.977486,2213.006701,3.821477e-03,0.314087
1,Sklearn LinearRegression,1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
2,Ridge (my),1343.758962,1131.838704,24638.677352,2658.639923,-2.909547e-04,0.010028
3,Lasso (my),1027.473802,818.627929,24588.983245,2220.633417,3.739979e-03,0.309351
4,ElasticNet (my),1290.697321,1078.236101,24632.805459,2608.316610,1.857674e-04,0.047151
5,Ridge sklearn,1247.379143,1049.426459,24567.313146,2193.897740,5.495199e-03,0.325881
6,Lasso sklearn,1243.515676,1045.181475,24567.321683,2191.810188,5.494508e-03,0.327163
7,ElasticNet sklearn,1180.504912,964.960460,24587.214126,2267.098200,3.883331e-03,0.280146
8,"Linear (MinMax, my)",1238.686682,1027.021494,24622.759240,2531.246918,1.001128e-03,0.102628
9,"Linear (MinMax, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
10,"Ridge (MinMax, my)",1419.984929,1208.756867,24647.435255,2732.049909,-1.002195e-03,-0.045396
11,"Ridge (MinMax, sklearn)",1247.519496,1049.259259,24567.316350,2194.405061,5.494940e-03,0.325569
12,"Lasso (MinMax, my)",1245.221413,1032.997801,24623.938350,2540.703747,9.054472e-04,0.095910
13,"Lasso (MinMax, sklearn)",1243.061515,1044.266393,24567.329587,2192.253178,5.493868e-03,0.326891
14,"ElasticNet (MinMax, my)",1405.224468,1193.967918,24646.043253,2719.894676,-8.891317e-04,-0.036115
15,"ElasticNet (MinMax, sklearn)",1508.694064,1286.219985,24620.553721,2576.776702,1.180085e-03,0.070055
16,"Linear (Standard, my)",1020.199609,814.426665,24586.978293,2206.687693,3.902440e-03,0.317998
17,"Linear (Standard, sklearn)",1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
18,"Ridge (Standard, my)",1297.667839,1086.299030,24633.199941,2606.041402,1.537441e-04,0.048812
19,"Ridge (Standard, sklearn)",1247.436706,1049.490334,24567.313144,2193.929511,5.495199e-03,0.325862
20,"Lasso (Standard, my)",1020.973155,814.667999,24587.408554,2210.063144,3.867577e-03,0.315910
21,"Lasso (Standard, sklearn)",1245.724495,1047.602257,24567.314388,2192.954703,5.495099e-03,0.326461
22,"ElasticNet (Standard, my)",1233.717847,1022.209662,24624.484808,2531.124773,8.611026e-04,0.102714
23,"ElasticNet (Standard, sklearn)",1141.851741,933.765971,24573.512098,2169.335938,4.993259e-03,0.340891
24,"Linear (Polynomial, degree=10, my)",3851.365543,3661.901637,24935.349300,4539.544017,-2.452479e-02,-1.886212
25,"Ridge (Polynomial, degree=10, my)",1219.714792,1009.927767,24615.474417,2408.368412,1.592162e-03,0.187638
26,"Lasso (Polynomial, degree=10, my)",1042.773064,830.040677,24596.768679,2339.823584,3.109002e-03,0.233222
27,"ElasticNet (Polynomial, degree=10, my)",1151.548265,942.197074,24605.402265,2299.295376,2.409052e-03,0.259554
28,"Linear (Polynomial, degree=10, sklearn)",1208.048000,16321.235427,24553.965817,961655.049046,6.575527e-03,-129520.638150
29,"Ridge (Polynomial, degree=10, sklearn)",1208.234210,1001.534720,24555.673150,2136.042106,6.437369e-03,0.360967
30,"Lasso (Polynomial, degree=10, sklearn)",1202.436440,996.056712,24556.084306,2104.681044,6.404097e-03,0.379594
31,"ElasticNet (Polynomial, degree=10, sklearn)",1092.901763,877.931186,24568.488199,2011.942803,5.400063e-03,0.433063
32,Naive Mean,1609.879132,1385.803971,24635.093764,2678.758284,-9.658940e-14,-0.005011
33,Naive Median,1442.898154,1230.142336,24645.554970,2723.903833,-8.494732e-04,-0.039172
34,Log func,1450.187821,1235.635929,24641.926891,2700.544437,-5.548243e-04,-0.021425
35,ElasticNet (outliers removed),806.924444,1235.635929,1190.192610,2700.544437,4.461407e-01,-0.021425
36,Naive Mean (outliers removed),1138.999587,1276.052477,1599.254339,2676.049545,-9.495353e-08,-0.002979
37,Linear (Analytical),1247.453521,1049.508675,24567.313144,2193.939162,5.495199e-03,0.325856
38,Linear (Batch GD),1218.769267,1016.778757,24567.802345,2178.238362,5.455592e-03,0.335470
39,Linear (Mini-batch GD),1253.756987,1052.026045,24571.045076,2221.262276,5.193033e-03,0.308960